fix: use channel as package name for generic_package upload
semantic-release/gitlab pull request #607
Opened 2023-09-28 07:21 UTC by phuocnb

The current `generic_package` upload does not satisfy what actual needs. We don't always release on the official `release` channel.

gitlab url format is
`/projects/:id/packages/generic/:package_name/:package_version/:file_name?status=:status`

What i did:
* `package_name` equal to `channel` (release, alpha, beta, rc, etc)
* `package_version` always requires in format `major.minor.patch` (required from gitlab generic package upload)
* `file_name` is treated as the label config (if the label value does not exist, it would take `version` value instead)

2023-09-28 10:45 UTC, phuocnb commented
It actually does not correct if the configuration provide a regex path (may match multiple files to upload). 
I will update the `file_name` to take the `basename` of actual uploading file instead of using label.

2023-09-28 20:01 UTC, JonasSchubert requested changes
IMO the option to configure the package name is a good idea.
But I would only provide this configuration option and would not change other functionalities.
Unit tests should be added, too.

2023-09-29 02:11 UTC, phuocnb commented on lib/publish.js
> +              `/projects/${encodedRepoId}/packages/generic/${encodedChannel}/${encodedVersion}/${encodedLabel}?${
This is my Package Registry on a private gitlab repo.

### The repo home page
 
![Screenshot from 2023-09-29 09-01-55](https://github.com/semantic-release/gitlab/assets/31727350/40b73e69-78e1-4ced-a5e9-9ddbad6bde48)

### The channel released assets
![Screenshot from 2023-09-29 09-02-46](https://github.com/semantic-release/gitlab/assets/31727350/40f5e5fe-843d-46ec-95f4-3e0a6ca6e16f)

![Screenshot from 2023-09-29 09-06-13](https://github.com/semantic-release/gitlab/assets/31727350/bdfc8307-9b58-46dd-b378-3b40ad5f3ec1)

You may notice that it is organized much better.

2023-09-29 02:14 UTC, phuocnb commented
> IMO the option to configure the package name is a good idea. But I would only provide this configuration option and would not change other functionalities. Unit tests should be added, too.

I would update the implementation and add unit tests later when the implementation has been approved.

2023-09-29 02:19 UTC, phuocnb commented on lib/publish.js
> +            const encodedLabel = encodeURIComponent(label ?? version);
I notice this too.

2023-09-29 11:39 UTC, JonasSchubert commented on lib/publish.js
> +              `/projects/${encodedRepoId}/packages/generic/${encodedChannel}/${encodedVersion}/${encodedLabel}?${
It does look clean and well organized, yes.\
My concerns are regarding users trying to use package names instead of channels.

2023-09-29 14:15 UTC, phuocnb commented on lib/publish.js
> +              `/projects/${encodedRepoId}/packages/generic/${encodedChannel}/${encodedVersion}/${encodedLabel}?${
I see.
It's better add it as an optional configuration.
Old users will not be forced to change their existing projects.

2023-10-02 07:04 UTC, fgreinacher commented on lib/publish.js
> +            const encodedLabel = encodeURIComponent(label ?? version);
I think `asset.label` can be templated, so that should be solvable via configuration, see https://github.com/semantic-release/gitlab#usage.

2023-10-02 07:06 UTC, fgreinacher commented on lib/publish.js
> +            const { major, minor, patch } = semver.parse(version);
Yes, this does not look correct. [GitLab allows much more](https://docs.gitlab.com/ee/user/packages/generic_packages/#publish-a-package-file):

> The package version. The following regex validates this: \A(\.?[\w\+-]+\.?)+\z. You can test your version strings on [Rubular](https://rubular.com/r/aNCV0wG5K14uq8).

2023-10-02 07:10 UTC, fgreinacher commented on lib/publish.js
> +              `/projects/${encodedRepoId}/packages/generic/${encodedChannel}/${encodedVersion}/${encodedLabel}?${
I like the structure too, but I would not enforce it to all users.

Maybe let's just a configuration option for `asset.packageName` and make that templatable. Then you could configure it something like this:

```json
{
  "branches": ["main"],
  "plugins": [
    [
      "@semantic-release/gitlab",
      {
        "assets": [
          { "path": "dist/asset.min.js", "label": "JS distribution", "target": "generic_package", "packageName": "${nextRelease.channel}" },
        ]
      }
    ]
  ]
}
```

2023-10-03 01:24 UTC, phuocnb commented on lib/publish.js
> +              `/projects/${encodedRepoId}/packages/generic/${encodedChannel}/${encodedVersion}/${encodedLabel}?${
@fgreinacher thank you for the suggestion.
I'm implementing it that way and will push new code soon.

2023-10-05 15:25 UTC, fgreinacher commented
> > IMO the option to configure the package name is a good idea. But I would only provide this configuration option and would not change other functionalities. Unit tests should be added, too.
> 
> I would update the implementation and add unit tests later when the implementation has been approved.

Feel free to go on!

2023-11-04 09:26 UTC, phuocnb commented
> > > IMO the option to configure the package name is a good idea. But I would only provide this configuration option and would not change other functionalities. Unit tests should be added, too.
> > 
> > 
> > I would update the implementation and add unit tests later when the implementation has been approved.
> 
> @phuocnb Feel free to go on and ping me if you're stuck somewhere!

I were so busy in the last 2 months.
I'm back to this today.

2023-11-08 08:19 UTC, phuocnb commented
@fgreinacher @JonasSchubert 
Depends on a testing project on gitlab, i'm pretty sure that this `label` config will not work in case of using `generic_package`

```
"@semantic-release/gitlab",
{
        "gitlabUrl": "https://gitlab.com",
        "assets": [
	        {
		        "path": "assets/single-file.md",
		        "label": "Single Label",
		        "target": "generic_package"
	        }
        ]
}
```

The upload request actually return a `400 HTTP Error` code.

This is the full job log
[failed-job.txt](https://github.com/semantic-release/gitlab/files/13293908/failed-job.txt)

-----------------------------------------------
After running the above job, the result is:
* A new tag has been created
* No release is created
* Nothing is uploaded to generic package

-----------------------------------------------
Changing the `label` value to match the filename and the job would be succeeded.

```
"@semantic-release/gitlab",
{
        "gitlabUrl": "https://gitlab.com",
        "assets": [
	        {
		        "path": "assets/single-file.md",
		        "label": "single-file.md",
		        "target": "generic_package"
	        }
        ]
}
```
-----------------------------------------------

In the `publish.js`:

_line 98-103_

``` 
uploadEndpoint = urlJoin(
              gitlabApiUrl,
              `/projects/${encodedRepoId}/packages/generic/release/${encodedVersion}/${encodedLabel}?${
                status ? `status=${status}&` : ""
              }select=package_file`
            );
```

_line 115-118_

``` 
const url = urlJoin(
              gitlabApiUrl,
              `/projects/${encodedRepoId}/packages/generic/release/${encodedVersion}/${encodedLabel}`
            );
```

I believe that `encodedLabel` should be changed to be `encodedFilename`.

This is the original issue that i want to commit a fix on this PR.

Anyway, i still working on this issue (on another branch).

2025-07-29 11:51 UTC, Rechem commented
Any updates on this ? I really need this feature for my workflow too

2025-08-06 04:58 UTC, phuocnb commented on lib/publish.js
> +            const encodedLabel = encodeURIComponent(label ?? version);
@JonasSchubert 

> IMO the fallback to the version is confusing. The version will then be the file name and package version

Since `asset.label` may be `undefined` 
```typescript
const label = asset.label ? template(asset.label)(context) : undefined;
```

fallback to `version` looks good to me.

2025-08-06 06:18 UTC, phuocnb commented on lib/publish.js
> +              `/projects/${encodedRepoId}/packages/generic/${encodedChannel}/${encodedVersion}/${encodedLabel}?${
@fgreinacher 
What do you think about this config instead?
```json
{
  "branches": ["main"],
  "plugins": [
    [
      "@semantic-release/gitlab",
      {
        "packageName": "${nextRelease.channel}",
        "assets": [
          {
            "path": "dist/asset.min.js",
            "label": "JS distribution",
            "target": "generic_package",
          }
        ]
      }
    ]
  ]
}
```

2025-08-07 19:57 UTC, fgreinacher commented
Thanks for getting back to this @phuocnb! The implementation looks fine at a first sight. Would you please update the PR description to match the implementation? Just to not confuse users that end up here from the changelog 😀 Thansk!

2025-08-19 08:18 UTC, JonasSchubert commented
@phuocnb Could you also revert your changes in the `package-lock.json`? Thanks a lot 🙇

2025-08-25 16:11 UTC, fgreinacher approved these changes

2025-08-25 16:23 UTC, merged